# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_email",
                    models.BooleanField(
                        default=True, verbose_name="Email Notifications"
                    ),
                ),
                (
                    "notification_telegram",
                    models.BooleanField(
                        default=False, verbose_name="Telegram Notifications"
                    ),
                ),
                (
                    "notification_push",
                    models.BooleanField(
                        default=False, verbose_name="Push Notifications"
                    ),
                ),
                (
                    "notification_discord",
                    models.BooleanField(
                        default=False, verbose_name="Discord Notifications"
                    ),
                ),
                (
                    "notification_slack",
                    models.BooleanField(
                        default=False, verbose_name="Slack Notifications"
                    ),
                ),
                (
                    "telegram_chat_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Telegram Chat ID"
                    ),
                ),
                (
                    "discord_webhook",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Discord Webhook URL"
                    ),
                ),
                (
                    "slack_webhook",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Slack Webhook URL"
                    ),
                ),
                (
                    "default_risk_profile",
                    models.CharField(
                        blank=True,
                        help_text="Name or type key of the user's default RiskProfile.",
                        max_length=20,
                        verbose_name="Default Risk Profile",
                    ),
                ),
                (
                    "default_strategy_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user's preferred strategy.",
                        null=True,
                        verbose_name="Default Strategy ID",
                    ),
                ),
                (
                    "auto_trading_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Auto-Trading Enabled"
                    ),
                ),
                (
                    "paper_trading_mode",
                    models.BooleanField(
                        default=False, verbose_name="Paper-Trading Mode"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "ordering": ["user__email"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "profile_picture",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Profile Picture URL"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Phone Number"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
                "ordering": ["user__email"],
            },
        ),
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Key Name")),
                (
                    "key_hash",
                    models.CharField(max_length=256, verbose_name="Key Hash (hashed)"),
                ),
                (
                    "key_prefix",
                    models.CharField(
                        help_text="First 8 characters of the raw key; safe to display in the UI.",
                        max_length=8,
                        verbose_name="Key Prefix",
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="List of permission scopes granted to this key, e.g. ['read:portfolio', 'write:orders'].",
                        verbose_name="Permissions",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Used At"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expires At"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User API Key",
                "verbose_name_plural": "User API Keys",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="users_usera_user_id_0dd2f2_idx",
                    ),
                    models.Index(
                        fields=["key_prefix"], name="users_usera_key_pre_0976b6_idx"
                    ),
                ],
            },
        ),
    ]
