# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketRegimeSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("STRONG_BULL", "Strong Bull Trend"),
                            ("WEAK_BULL", "Weak Bull Trend"),
                            ("STRONG_BEAR", "Strong Bear Trend"),
                            ("WEAK_BEAR", "Weak Bear Trend"),
                            ("SIDEWAYS", "Sideways Range"),
                            ("HIGH_VOL", "High Volatility"),
                            ("LOW_VOL", "Low Volatility"),
                            ("NEWS_DRIVEN", "News-Driven Market"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("btc_trend", models.CharField(blank=True, max_length=20)),
                ("eth_trend", models.CharField(blank=True, max_length=20)),
                (
                    "dominance_btc",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "fear_greed_index",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="0-100 Fear & Greed Index value.",
                        null=True,
                    ),
                ),
                ("factors", models.JSONField(default=dict)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Market Regime Snapshot",
                "verbose_name_plural": "Market Regime Snapshots",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="AIScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Overall opportunity quality score (0–100).",
                        max_digits=5,
                    ),
                ),
                (
                    "risk_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Risk level score (0=low risk, 100=extreme risk).",
                        max_digits=5,
                    ),
                ),
                (
                    "momentum_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "volume_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "trend_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "structure_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("HOLD", "Hold"),
                            ("IGNORE", "Ignore"),
                        ],
                        default="IGNORE",
                        max_length=10,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("EXTREME", "Extreme"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "market_regime",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_BULL", "Strong Bull Trend"),
                            ("WEAK_BULL", "Weak Bull Trend"),
                            ("STRONG_BEAR", "Strong Bear Trend"),
                            ("WEAK_BEAR", "Weak Bear Trend"),
                            ("SIDEWAYS", "Sideways Range"),
                            ("HIGH_VOL", "High Volatility"),
                            ("LOW_VOL", "Low Volatility"),
                            ("NEWS_DRIVEN", "News-Driven Market"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "entry_zone_low",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "entry_zone_high",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "stop_loss_suggest",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "tp1_suggest",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "tp2_suggest",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "tp3_suggest",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "risk_reward_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "supporting_factors",
                    models.JSONField(
                        default=list,
                        help_text="List of factor names that contributed positively.",
                    ),
                ),
                (
                    "conflicting_factors",
                    models.JSONField(
                        default=list,
                        help_text="List of factor names that reduced confidence.",
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="Human-readable explanation."
                    ),
                ),
                (
                    "mtf_alignment",
                    models.JSONField(
                        default=dict,
                        help_text='e.g. {"5m":"BULLISH","15m":"BULLISH","1h":"SIDEWAYS"}',
                    ),
                ),
                (
                    "compatible_strategies",
                    models.JSONField(
                        default=list,
                        help_text="Strategy slugs compatible with this setup.",
                    ),
                ),
                ("timeframe", models.CharField(default="1h", max_length=10)),
                (
                    "is_automated",
                    models.BooleanField(
                        default=False,
                        help_text="True if this score triggered an automated trade.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_scores",
                        to="market.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Score",
                "verbose_name_plural": "AI Scores",
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="AILearningRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        choices=[
                            ("BUY", "Buy"),
                            ("SELL", "Sell"),
                            ("HOLD", "Hold"),
                            ("IGNORE", "Ignore"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "confidence_at_signal",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "risk_level_at_signal",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("EXTREME", "Extreme"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "market_regime_at_signal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("STRONG_BULL", "Strong Bull Trend"),
                            ("WEAK_BULL", "Weak Bull Trend"),
                            ("STRONG_BEAR", "Strong Bear Trend"),
                            ("WEAK_BEAR", "Weak Bear Trend"),
                            ("SIDEWAYS", "Sideways Range"),
                            ("HIGH_VOL", "High Volatility"),
                            ("LOW_VOL", "Low Volatility"),
                            ("NEWS_DRIVEN", "News-Driven Market"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "was_executed",
                    models.BooleanField(
                        default=False, help_text="Did the user execute this trade?"
                    ),
                ),
                (
                    "trade_outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WIN", "Win"),
                            ("LOSS", "Loss"),
                            ("BREAKEVEN", "Breakeven"),
                            ("SKIPPED", "Skipped"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "actual_pnl_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                ("strategy_used", models.CharField(blank=True, max_length=50)),
                (
                    "feature_snapshot",
                    models.JSONField(
                        default=dict, help_text="All indicator values at signal time."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="market.tradingpair",
                    ),
                ),
                (
                    "ai_score",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_records",
                        to="ai_engine.aiscore",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Learning Record",
                "verbose_name_plural": "AI Learning Records",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(
                fields=["trading_pair", "-created_at"],
                name="ai_engine_a_trading_9fed31_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(
                fields=["direction", "-created_at"],
                name="ai_engine_a_directi_e51e12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(
                fields=["confidence_score", "direction"],
                name="ai_engine_a_confide_66beb9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailearningrecord",
            index=models.Index(
                fields=["trading_pair", "-created_at"],
                name="ai_engine_a_trading_ca5934_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ailearningrecord",
            index=models.Index(
                fields=["recommendation", "trade_outcome"],
                name="ai_engine_a_recomme_9e16e0_idx",
            ),
        ),
    ]
