# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScannerJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("pairs_scanned", models.PositiveIntegerField(default=0)),
                ("candidates_found", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Scan duration in milliseconds."
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system-triggered scans.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scanner_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scanner Job",
                "verbose_name_plural": "Scanner Jobs",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScannerResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "risk_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("BULLISH", "Bullish"),
                            ("BEARISH", "Bearish"),
                            ("SIDEWAYS", "Sideways"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                    ),
                ),
                (
                    "rsi_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("macd_signal", models.CharField(blank=True, max_length=20)),
                (
                    "volume_24h_usdt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=24, null=True
                    ),
                ),
                ("volume_spike", models.BooleanField(default=False)),
                (
                    "spread_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "btc_correlation",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "eth_correlation",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                (
                    "factors",
                    models.JSONField(
                        default=dict,
                        help_text="Key indicator values that contributed to the score.",
                    ),
                ),
                ("is_candidate", models.BooleanField(db_index=True, default=False)),
                ("rejection_reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "scanner_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="scanner.scannerjob",
                    ),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanner_results",
                        to="market.tradingpair",
                    ),
                ),
            ],
            options={
                "verbose_name": "Scanner Result",
                "verbose_name_plural": "Scanner Results",
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.CreateModel(
            name="ScannerSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "min_volume_usdt",
                    models.DecimalField(
                        decimal_places=2,
                        default=500000,
                        help_text="Minimum 24h volume in USDT.",
                        max_digits=20,
                    ),
                ),
                (
                    "min_liquidity_score",
                    models.DecimalField(decimal_places=2, default=50, max_digits=5),
                ),
                (
                    "max_spread_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.5,
                        help_text="Maximum bid-ask spread as a percentage.",
                        max_digits=6,
                    ),
                ),
                (
                    "volatility_min",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.005,
                        help_text="Minimum ATR/price ratio.",
                        max_digits=6,
                    ),
                ),
                (
                    "volatility_max",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.15,
                        help_text="Maximum ATR/price ratio.",
                        max_digits=6,
                    ),
                ),
                ("require_trend", models.BooleanField(default=True)),
                ("require_volume_spike", models.BooleanField(default=False)),
                (
                    "min_rsi",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "max_rsi",
                    models.DecimalField(decimal_places=2, default=70, max_digits=5),
                ),
                (
                    "min_confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=60,
                        help_text="Minimum score to be listed as a candidate.",
                        max_digits=5,
                    ),
                ),
                ("scan_interval_seconds", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enabled_exchanges",
                    models.JSONField(
                        default=list, help_text='e.g. ["binance", "bybit"]'
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scanner_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scanner Settings",
                "verbose_name_plural": "Scanner Settings",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="scannerjob",
            index=models.Index(
                fields=["tenant_id", "status"], name="scanner_sca_tenant__38ecd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scannerjob",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="scanner_sca_tenant__afbe1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scannerresult",
            index=models.Index(
                fields=["scanner_job", "is_candidate"],
                name="scanner_sca_scanner_5b9a2d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scannerresult",
            index=models.Index(
                fields=["trading_pair", "-created_at"],
                name="scanner_sca_trading_eae7bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scannerresult",
            index=models.Index(
                fields=["scanner_job", "-confidence_score"],
                name="scanner_sca_scanner_c9b543_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scannersettings",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="scanner_sca_tenant__e2b82a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scannersettings",
            index=models.Index(
                fields=["tenant_id", "deleted_at"],
                name="scanner_sca_tenant__52ffdd_idx",
            ),
        ),
    ]
