# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        ("risk", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "strategy_type",
                    models.CharField(
                        choices=[
                            ("TREND_FOLLOWING", "Trend Following"),
                            ("BREAKOUT", "Breakout"),
                            ("PULLBACK", "Pullback"),
                            ("MOMENTUM", "Momentum"),
                            ("SWING", "Swing Trading"),
                            ("SCALPING", "Scalping"),
                            ("GRID", "Grid Trading"),
                            ("DCA", "Dollar Cost Averaging"),
                            ("MEAN_REVERSION", "Mean Reversion"),
                            ("NEWS_REACTION", "News Reaction"),
                            ("SMC", "Smart Money Concepts"),
                            ("ICT", "ICT Concepts"),
                            ("CUSTOM", "Custom Strategy"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "suitable_regimes",
                    models.JSONField(
                        default=list,
                        help_text='List of MarketRegime values. e.g. ["STRONG_BULL", "WEAK_BULL"]',
                    ),
                ),
                ("unsuitable_regimes", models.JSONField(default=list)),
                ("min_timeframe", models.CharField(default="5m", max_length=10)),
                ("max_timeframe", models.CharField(default="1d", max_length=10)),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict,
                        help_text="JSON Schema for user configuration options.",
                    ),
                ),
                ("default_params", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("requires_premium", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserStrategy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="User-defined name for this configuration.",
                        max_length=100,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text="User overrides for strategy parameters.",
                    ),
                ),
                (
                    "timeframes",
                    models.JSONField(default=list, help_text='e.g. ["5m","15m","1h"]'),
                ),
                (
                    "trading_pairs",
                    models.JSONField(
                        default=list,
                        help_text="Specific pairs to trade, empty = use scanner.",
                    ),
                ),
                (
                    "exchanges",
                    models.JSONField(
                        default=list, help_text="Exchange account IDs to use."
                    ),
                ),
                (
                    "automation_level",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual (Signals Only)"),
                            ("SEMI_AUTO", "Semi-Automatic (Confirm Before Execute)"),
                            ("FULL_AUTO", "Fully Automatic"),
                        ],
                        default="SEMI_AUTO",
                        max_length=20,
                    ),
                ),
                (
                    "min_confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=70,
                        help_text="Minimum AI confidence to execute a trade.",
                        max_digits=5,
                    ),
                ),
                ("max_trades_per_day", models.PositiveSmallIntegerField(default=10)),
                (
                    "trading_sessions",
                    models.JSONField(
                        default=list,
                        help_text='e.g. [{"start":"09:00","end":"17:00","timezone":"UTC"}]',
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_paper_mode",
                    models.BooleanField(
                        default=False, help_text="If True, only paper trades."
                    ),
                ),
                (
                    "risk_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_strategies",
                        to="risk.riskprofile",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_instances",
                        to="strategies.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Strategy",
                "verbose_name_plural": "User Strategies",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StrategyPerformance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("total_trades", models.PositiveIntegerField(default=0)),
                ("winning_trades", models.PositiveIntegerField(default=0)),
                ("losing_trades", models.PositiveIntegerField(default=0)),
                (
                    "win_rate_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "avg_win_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "avg_loss_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "profit_factor",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Gross profit / Gross loss",
                        max_digits=8,
                    ),
                ),
                (
                    "total_pnl_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_commission_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "net_pnl_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "sharpe_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "sortino_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "calmar_ratio",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "recovery_factor",
                    models.DecimalField(decimal_places=4, default=0, max_digits=8),
                ),
                (
                    "avg_holding_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("first_trade_at", models.DateTimeField(blank=True, null=True)),
                ("last_trade_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_performances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance",
                        to="strategies.userstrategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Performance",
                "verbose_name_plural": "Strategy Performances",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BacktestJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("timeframe", models.CharField(default="1h", max_length=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "initial_balance",
                    models.DecimalField(decimal_places=2, default=10000, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        default=dict, help_text="Backtest result summary."
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="backtest_jobs",
                        to="market.tradingpair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backtest_jobs",
                        to="strategies.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Backtest Job",
                "verbose_name_plural": "Backtest Jobs",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "-created_at"],
                        name="strategies__tenant__7e3c79_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "deleted_at"],
                        name="strategies__tenant__c33294_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="userstrategy",
            index=models.Index(
                fields=["user", "is_active"], name="strategies__user_id_f1b842_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="strategyperformance",
            index=models.Index(
                fields=["tenant_id", "-created_at"],
                name="strategies__tenant__8f4817_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="strategyperformance",
            index=models.Index(
                fields=["tenant_id", "deleted_at"],
                name="strategies__tenant__176a0b_idx",
            ),
        ),
    ]
