# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRADE_EXECUTED", "Trade Executed"),
                            ("POSITION_CLOSED", "Position Closed"),
                            ("STOP_LOSS_TRIGGERED", "Stop Loss Triggered"),
                            ("TAKE_PROFIT_REACHED", "Take Profit Reached"),
                            ("API_FAILURE", "API Failure"),
                            ("EXCHANGE_OFFLINE", "Exchange Offline"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("RISK_WARNING", "Risk Warning"),
                            ("EMERGENCY_STOP", "Emergency Stop"),
                            ("SCANNER_ALERT", "Scanner Alert"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("BILLING_EVENT", "Billing Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "payload",
                    models.JSONField(
                        default=dict,
                        help_text="Structured data for rendering (e.g. trade details).",
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("TELEGRAM", "Telegram"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PUSH", "Push Notification"),
                            ("DISCORD", "Discord"),
                            ("SLACK", "Slack"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped (Channel Disabled)"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Message ID from external service.",
                        max_length=256,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Delivery",
                "verbose_name_plural": "Notification Deliveries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRADE_EXECUTED", "Trade Executed"),
                            ("POSITION_CLOSED", "Position Closed"),
                            ("STOP_LOSS_TRIGGERED", "Stop Loss Triggered"),
                            ("TAKE_PROFIT_REACHED", "Take Profit Reached"),
                            ("API_FAILURE", "API Failure"),
                            ("EXCHANGE_OFFLINE", "Exchange Offline"),
                            ("DAILY_SUMMARY", "Daily Summary"),
                            ("RISK_WARNING", "Risk Warning"),
                            ("EMERGENCY_STOP", "Emergency Stop"),
                            ("SCANNER_ALERT", "Scanner Alert"),
                            ("SYSTEM_ALERT", "System Alert"),
                            ("BILLING_EVENT", "Billing Event"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("TELEGRAM", "Telegram"),
                            ("WHATSAPP", "WhatsApp"),
                            ("PUSH", "Push Notification"),
                            ("DISCORD", "Discord"),
                            ("SLACK", "Slack"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Email subject / Telegram title.",
                        max_length=255,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Template body. Use {{variable}} placeholders."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["event_type", "channel"],
                "unique_together": {("event_type", "channel")},
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_f2ad08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="notificatio_event_t_bb6b48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["notification", "channel"],
                name="notificatio_notific_7707f8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "-created_at"], name="notificatio_status_48a826_idx"
            ),
        ),
    ]
