# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchanges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "total_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "available_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "locked_balance",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Balance locked in open orders/positions.",
                        max_digits=24,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "total_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "initial_balance",
                    models.DecimalField(
                        decimal_places=8,
                        default=0,
                        help_text="Balance when the portfolio was first connected.",
                        max_digits=24,
                    ),
                ),
                (
                    "peak_balance",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("is_paper", models.BooleanField(default=False)),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to="exchanges.exchangeaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PortfolioAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset", models.CharField(db_index=True, max_length=20)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "avg_buy_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "current_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "value_usdt",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "allocation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="% of total portfolio value.",
                        max_digits=6,
                    ),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                (
                    "unrealized_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio Asset",
                "verbose_name_plural": "Portfolio Assets",
                "ordering": ["-value_usdt"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_balance", models.DecimalField(decimal_places=8, max_digits=24)),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=24),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio History",
                "verbose_name_plural": "Portfolio History",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="PnLHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "daily_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "cumulative_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "portfolio_value",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("trade_count", models.PositiveIntegerField(default=0)),
                ("win_count", models.PositiveIntegerField(default=0)),
                ("loss_count", models.PositiveIntegerField(default=0)),
                (
                    "win_rate_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "exchange_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pnl_history",
                        to="exchanges.exchangeaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pnl_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PnL History",
                "verbose_name_plural": "PnL History",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="portfolio_p_user_id_9bd023_idx"
                    )
                ],
                "unique_together": {("user", "exchange_account", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="portfolio",
            index=models.Index(fields=["user"], name="portfolio_p_user_id_24fc7a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("user", "exchange_account")},
        ),
        migrations.AlterUniqueTogether(
            name="portfolioasset",
            unique_together={("portfolio", "asset")},
        ),
        migrations.AddIndex(
            model_name="portfoliohistory",
            index=models.Index(
                fields=["portfolio", "-recorded_at"],
                name="portfolio_p_portfol_361da6_idx",
            ),
        ),
    ]
