# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchanges", "0001_initial"),
        ("market", "0001_initial"),
        ("strategies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        db_index=True,
                        help_text="Prevents duplicate order submission during retries.",
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "client_order_id",
                    models.CharField(
                        blank=True,
                        help_text="Our generated ID sent to the exchange.",
                        max_length=128,
                    ),
                ),
                (
                    "exchange_order_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Order ID returned by the exchange.",
                        max_length=256,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=10
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                            ("STOP_LIMIT", "Stop Limit"),
                            ("OCO", "OCO"),
                            ("TRAILING_STOP", "Trailing Stop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("SUBMITTED", "Submitted to Exchange"),
                            ("ACCEPTED", "Accepted by Exchange"),
                            ("FILLED", "Filled"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="Null for market orders.",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "trailing_delta",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Trailing stop delta as %.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "average_fill_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("commission_asset", models.CharField(blank=True, max_length=20)),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "risk_reward_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "risk_amount_usdt",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("is_paper_trade", models.BooleanField(db_index=True, default=False)),
                ("is_backtest", models.BooleanField(default=False)),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False,
                        help_text="True if placed manually by user, not by automation.",
                    ),
                ),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ai_reasoning", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="exchanges.exchangeaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="strategies.strategy",
                    ),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="market.tradingpair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                (
                    "old_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Created"),
                            ("SUBMITTED", "Submitted to Exchange"),
                            ("ACCEPTED", "Accepted by Exchange"),
                            ("FILLED", "Filled"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CREATED", "Created"),
                            ("SUBMITTED", "Submitted to Exchange"),
                            ("ACCEPTED", "Accepted by Exchange"),
                            ("FILLED", "Filled"),
                            ("PARTIALLY_FILLED", "Partially Filled"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "exchange_data",
                    models.JSONField(
                        default=dict, help_text="Raw exchange response for this event."
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order Event",
                "verbose_name_plural": "Order Events",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("CLOSED", "Closed"),
                            ("PARTIALLY_CLOSED", "Partially Closed"),
                        ],
                        db_index=True,
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "current_price",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                (
                    "unrealized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "realized_pnl",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "commission_paid",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("leverage", models.PositiveSmallIntegerField(default=1)),
                (
                    "margin",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "liquidation_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "stop_loss_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "trailing_stop_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "trailing_stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("break_even_triggered", models.BooleanField(default=False)),
                ("partial_close_done", models.BooleanField(default=False)),
                ("is_paper_trade", models.BooleanField(db_index=True, default=False)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_confidence",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "entry_order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="opened_position",
                        to="orders.order",
                    ),
                ),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="exchanges.exchangeaccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="strategies.strategy",
                    ),
                ),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="market.tradingpair",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["user", "status"], name="orders_orde_user_id_02a211_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["exchange_account", "status"],
                name="orders_orde_exchang_f31db3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["trading_pair", "-created_at"],
                name="orders_orde_trading_213a56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["exchange_order_id"], name="orders_orde_exchang_4b743c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["idempotency_key"], name="orders_orde_idempot_ab5556_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["is_paper_trade", "status"],
                name="orders_orde_is_pape_86deca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_4c5f76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["user", "status"], name="orders_posi_user_id_10f3b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["exchange_account", "status"],
                name="orders_posi_exchang_111fa2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["trading_pair", "status"], name="orders_posi_trading_bc5ceb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["is_paper_trade", "status"],
                name="orders_posi_is_pape_736150_idx",
            ),
        ),
    ]
