# Generated by Django 5.0.6 on 2026-07-08 13:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="Logo URL"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "supports_futures",
                    models.BooleanField(default=False, verbose_name="Supports Futures"),
                ),
                (
                    "supports_spot",
                    models.BooleanField(default=True, verbose_name="Supports Spot"),
                ),
                (
                    "supports_websocket",
                    models.BooleanField(
                        default=False, verbose_name="Supports WebSocket"
                    ),
                ),
                (
                    "sandbox_available",
                    models.BooleanField(
                        default=False, verbose_name="Sandbox Available"
                    ),
                ),
                (
                    "phase",
                    models.IntegerField(
                        default=1,
                        help_text="1 = Phase 1 (core), 2 = Phase 2 (extended).",
                        verbose_name="Integration Phase",
                    ),
                ),
                (
                    "api_docs_url",
                    models.URLField(
                        blank=True, max_length=512, verbose_name="API Docs URL"
                    ),
                ),
                (
                    "rate_limit_per_minute",
                    models.IntegerField(default=60, verbose_name="Rate Limit / Minute"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Exchange",
                "verbose_name_plural": "Exchanges",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="exchanges_e_slug_7a755a_idx"),
                    models.Index(
                        fields=["is_active", "phase"],
                        name="exchanges_e_is_acti_013c84_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "api_key_encrypted",
                    models.TextField(verbose_name="API Key (encrypted)"),
                ),
                (
                    "api_secret_encrypted",
                    models.TextField(verbose_name="API Secret (encrypted)"),
                ),
                (
                    "api_passphrase_encrypted",
                    models.TextField(
                        blank=True,
                        help_text="Required by some exchanges (e.g., KuCoin).",
                        verbose_name="API Passphrase (encrypted)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_testnet",
                    models.BooleanField(
                        default=False, verbose_name="Testnet / Sandbox"
                    ),
                ),
                (
                    "permissions",
                    models.JSONField(
                        default=list,
                        help_text="Exchange-reported permissions for this API key.",
                        verbose_name="Permissions",
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Synced At"
                    ),
                ),
                (
                    "balance_synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Balance Synced At"
                    ),
                ),
                (
                    "connection_status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("ERROR", "Error"),
                            ("TESTING", "Testing"),
                        ],
                        default="DISCONNECTED",
                        max_length=20,
                        verbose_name="Connection Status",
                    ),
                ),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounts",
                        to="exchanges.exchange",
                        verbose_name="Exchange",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_accounts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Account",
                "verbose_name_plural": "Exchange Accounts",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExchangeConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "connected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Connected At"
                    ),
                ),
                (
                    "disconnected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Disconnected At"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONNECTED", "Connected"),
                            ("DISCONNECTED", "Disconnected"),
                            ("ERROR", "Error"),
                            ("TESTING", "Testing"),
                        ],
                        default="CONNECTED",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                (
                    "websocket_session_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="WebSocket Session ID"
                    ),
                ),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="exchanges.exchangeaccount",
                        verbose_name="Exchange Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Connection",
                "verbose_name_plural": "Exchange Connections",
                "ordering": ["-connected_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=128, verbose_name="Action")),
                (
                    "request_data",
                    models.JSONField(default=dict, verbose_name="Request Data"),
                ),
                (
                    "response_data",
                    models.JSONField(default=dict, verbose_name="Response Data"),
                ),
                ("status_code", models.IntegerField(verbose_name="HTTP Status Code")),
                ("latency_ms", models.IntegerField(verbose_name="Latency (ms)")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Error Message"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "exchange_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="exchanges.exchangeaccount",
                        verbose_name="Exchange Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange Log",
                "verbose_name_plural": "Exchange Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exchangeaccount",
            index=models.Index(
                fields=["user", "exchange"], name="exchanges_e_user_id_22d7ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeaccount",
            index=models.Index(
                fields=["tenant_id", "is_active"], name="exchanges_e_tenant__2f19fb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeaccount",
            index=models.Index(
                fields=["connection_status"], name="exchanges_e_connect_bccd0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeconnection",
            index=models.Index(
                fields=["exchange_account", "status"],
                name="exchanges_e_exchang_a79db8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangeconnection",
            index=models.Index(
                fields=["connected_at"], name="exchanges_e_connect_66f4e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exchangelog",
            index=models.Index(
                fields=["exchange_account", "action"],
                name="exchanges_e_exchang_e27194_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangelog",
            index=models.Index(
                fields=["exchange_account", "created_at"],
                name="exchanges_e_exchang_f1b240_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exchangelog",
            index=models.Index(
                fields=["status_code"], name="exchanges_e_status__1844a8_idx"
            ),
        ),
    ]
