# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Profile Name")),
                (
                    "profile_type",
                    models.CharField(
                        choices=[
                            ("CONSERVATIVE", "Conservative"),
                            ("MODERATE", "Moderate"),
                            ("AGGRESSIVE", "Aggressive"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="MODERATE",
                        max_length=20,
                    ),
                ),
                (
                    "max_risk_per_trade_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=1.0,
                        help_text="Maximum % of portfolio balance to risk on a single trade.",
                        max_digits=5,
                    ),
                ),
                (
                    "max_daily_loss_pct",
                    models.DecimalField(decimal_places=2, default=2.0, max_digits=5),
                ),
                (
                    "max_weekly_loss_pct",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "max_monthly_loss_pct",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("max_open_positions", models.PositiveIntegerField(default=5)),
                (
                    "max_portfolio_exposure_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Max % of portfolio in open positions.",
                        max_digits=5,
                    ),
                ),
                (
                    "max_single_position_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=20.0,
                        help_text="Max % of portfolio in a single position.",
                        max_digits=5,
                    ),
                ),
                (
                    "max_drawdown_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=15.0,
                        help_text="Auto-pause trading if drawdown exceeds this %.",
                        max_digits=5,
                    ),
                ),
                ("max_consecutive_losses", models.PositiveIntegerField(default=3)),
                (
                    "consecutive_loss_cooldown_mins",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Pause trading for this many minutes after hitting max consecutive losses.",
                    ),
                ),
                ("trailing_stop_enabled", models.BooleanField(default=True)),
                ("break_even_enabled", models.BooleanField(default=True)),
                ("partial_profit_enabled", models.BooleanField(default=True)),
                (
                    "partial_profit_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="% of position to close at first take-profit level.",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Exactly one profile per user should be marked as default.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Profile",
                "verbose_name_plural": "Risk Profiles",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RiskViolationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rule_name", models.CharField(db_index=True, max_length=100)),
                (
                    "rule_value",
                    models.CharField(
                        blank=True, help_text="Configured limit.", max_length=100
                    ),
                ),
                (
                    "actual_value",
                    models.CharField(
                        blank=True,
                        help_text="Actual value that triggered the violation.",
                        max_length=100,
                    ),
                ),
                (
                    "order_data",
                    models.JSONField(
                        default=dict, help_text="Snapshot of the rejected order."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "risk_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="risk.riskprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_violations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Risk Violation Log",
                "verbose_name_plural": "Risk Violation Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyLossTracker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "realized_loss",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "unrealized_loss",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("trades_count", models.PositiveIntegerField(default=0)),
                ("is_limit_reached", models.BooleanField(db_index=True, default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_loss_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Loss Tracker",
                "verbose_name_plural": "Daily Loss Trackers",
                "ordering": ["-date"],
                "unique_together": {("user", "date")},
            },
        ),
        migrations.CreateModel(
            name="DrawdownHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("max_balance", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=8, max_digits=20),
                ),
                ("drawdown_pct", models.DecimalField(decimal_places=2, max_digits=6)),
                ("recorded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawdown_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Drawdown History",
                "verbose_name_plural": "Drawdown History",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-recorded_at"],
                        name="risk_drawdo_user_id_0ae7bb_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmergencyStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4).",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="The tenant this record belongs to.",
                        verbose_name="Tenant ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created (UTC).",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last update (UTC).",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "created_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who created this record.",
                        null=True,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the user who last modified this record.",
                        null=True,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Monotonically increasing version counter used for optimistic locking. Increment this on every meaningful business-logic save.",
                        verbose_name="Version",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Non-null when the record has been soft-deleted (UTC).",
                        null=True,
                        verbose_name="Deleted At",
                    ),
                ),
                (
                    "triggered_by",
                    models.CharField(
                        choices=[
                            ("USER", "User Triggered"),
                            ("SYSTEM", "System Triggered"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(help_text="Why was the emergency stop triggered?"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("resumed_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_stops",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Stop",
                "verbose_name_plural": "Emergency Stops",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="risk_emerge_user_id_4f2f8b_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="riskprofile",
            index=models.Index(
                fields=["user", "is_active"], name="risk_riskpr_user_id_5bceb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskprofile",
            index=models.Index(
                fields=["user", "is_default"], name="risk_riskpr_user_id_76399c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskviolationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="risk_riskvi_user_id_1bc36d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskviolationlog",
            index=models.Index(
                fields=["rule_name", "-created_at"],
                name="risk_riskvi_rule_na_cd94cf_idx",
            ),
        ),
    ]
