# Generated by Django 5.0.6 on 2026-07-08 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exchanges", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TradingPair",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="e.g. BTCUSDT, ETH-PERP",
                        max_length=30,
                        verbose_name="Symbol",
                    ),
                ),
                (
                    "base_asset",
                    models.CharField(max_length=20, verbose_name="Base Asset"),
                ),
                (
                    "quote_asset",
                    models.CharField(max_length=20, verbose_name="Quote Asset"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "is_futures",
                    models.BooleanField(default=False, verbose_name="Futures Contract"),
                ),
                (
                    "min_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="Min Quantity",
                    ),
                ),
                (
                    "max_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="Max Quantity",
                    ),
                ),
                (
                    "quantity_step",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="Quantity Step",
                    ),
                ),
                (
                    "price_step",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="Price Step",
                    ),
                ),
                (
                    "min_notional",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=30,
                        null=True,
                        verbose_name="Min Notional",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trading_pairs",
                        to="exchanges.exchange",
                        verbose_name="Exchange",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trading Pair",
                "verbose_name_plural": "Trading Pairs",
                "ordering": ["exchange", "symbol"],
            },
        ),
        migrations.CreateModel(
            name="Ticker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "bid",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "ask",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "high_24h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "low_24h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "volume_24h",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=30, null=True
                    ),
                ),
                (
                    "change_24h_pct",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickers",
                        to="market.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=8, max_digits=30)),
                ("timestamp", models.DateTimeField()),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="open_interests",
                        to="market.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OHLCV",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1m", "1 Minute"),
                            ("5m", "5 Minutes"),
                            ("15m", "15 Minutes"),
                            ("1h", "1 Hour"),
                            ("4h", "4 Hours"),
                            ("1d", "1 Day"),
                        ],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("open", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.DecimalField(decimal_places=8, max_digits=30)),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ohlcv",
                        to="market.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Liquidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("side", models.CharField(max_length=10)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=30)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("timestamp", models.DateTimeField()),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidations",
                        to="market.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FundingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("timestamp", models.DateTimeField()),
                (
                    "trading_pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funding_rates",
                        to="market.tradingpair",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tradingpair",
            index=models.Index(
                fields=["symbol", "is_active"], name="market_trad_symbol_97a684_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tradingpair",
            index=models.Index(
                fields=["exchange", "is_futures"], name="market_trad_exchang_4794cc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tradingpair",
            unique_together={("exchange", "symbol")},
        ),
    ]
